<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <AssemblyName>ATASMultiSignal</AssemblyName>
    <RootNamespace>ATASMultiSignal</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>10</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="ATAS.Indicators">
      <HintPath>$(ATASSdkPath)\ATAS.Indicators.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OFT.Core">
      <HintPath>$(ATASSdkPath)\OFT.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OFT.Rendering">
      <HintPath>$(ATASSdkPath)\OFT.Rendering.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
